### ISSUE TITLE
You are trying to load a weight file containing 109 layers into a model with 103 layers.

### ISSUE THREAD

**Issue by huberemanuel** [chunchentu/facial_expression#1]
I've downloaded the model that is on the README file, then run the following command
`python3 verify_model.py  --model_weights resnet50_weights.h5`
And get the following message:
`Traceback (most recent call last):
  File "verify_model.py", line 32, in <module>
    data, model = FACIAL(), FACIALModel(args["model_weights"], use_log=False)
  File "/home/emanuel/Projects/Github/Me/facial_expression/setup_facial.py", line 108, in __init__
    model.load_weights(restore)
  File "/home/emanuel/.local/lib/python3.6/site-packages/keras/engine/topology.py", line 2622, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/home/emanuel/.local/lib/python3.6/site-packages/keras/engine/topology.py", line 3116, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 109 layers into a model with 103 layers.`

Shouldn't those weights have 103 layers?

EDIT1: This happen with the first model available to download

**Comment by chunchentu** [comment]
Hi, I update the verify model script to support the first model (image size = 200x200)
You can calculate the model performance by
```bash
python3 verify_model.py --model_weights resnet_weights.h5 --image_size 200
```
Thanks for reporting.
